version: "3.9"
services:
  fastapi:
    build:
      context: ./python
      target: fastapi
    ports:
      - 8000:8000

  flask:
    build:
      context: ./python
      target: flask
    ports:
      - 5000:5000

  echo:
    build:
      context: ./golang
      target: echo
    ports:
      - 1323:1323

  gin:
    build:
      context: ./golang
      target: gin
    ports:
      - 8080:8080